on:
  workflow_dispatch:
  push:
  schedule:
    #- cron:  '17 */2 * * *'
    - cron:  '*/10 * * * *'

permissions: write-all

name: Automated Releases
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Timestamp
        id: date
        run: |
          echo "UNIXTIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.UNIXTIMESTAMP }}
          tag_exists_error: false
          message: "Automated Release."
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.UNIXTIMESTAMP }}
          release_name: Release ${{ env.UNIXTIMESTAMP }}
          body: |
            Automated Release.
          draft: false
          prerelease: false
